name: Build

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout artifact
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync

      - name: Extract version
        id: vars
        shell: bash
        run: |
          if [[ "${GITHUB_REF_NAME}" =~ ^v[0-9] ]]; then
            echo "CLEAN_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          else
            echo "CLEAN_VERSION=0.0.1" >> $GITHUB_ENV
          fi

      - name: Build with Nuitka
        run: >
          uv run nuitka
          --standalone
          --windows-disable-console
          --assume-yes-for-downloads
          --enable-plugin=pyside6
          --output-dir=dist
          --output-filename=pyscripts
          --product-name=pyscripts
          --file-version=${{ env.CLEAN_VERSION }}
          main.py

      - name: Setup MSVC command prompt
        if: runner.os == 'Windows'
        uses: step-security/msvc-dev-cmd@v1

      - name: Compile launcher (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: MSYS2_ARG_CONV_EXCL="*" cl /O2 /Fe:dist/pyscripts.exe /source-charset:utf-8 build/launcher.c

      - name: Compile launcher (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "macOS" ]; then
            cc -O2 -o dist/pyscripts build/launcher.c
          else
            gcc -O2 -o dist/pyscripts build/launcher.c
          fi

      - name: Restructure package
        shell: bash
        run: ./build/restructure.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: pyscripts-${{ matrix.os }}-${{ github.ref_name }}
          path: dist/package/
